name = "Con2Prim"
uuid = "0c6c750e-2bec-4ac6-a609-2817dcb5d263"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.6.0"
NonlinearSolve = "4.5.0"
StaticArrays = "1.9.13"
julia = "1.6"
